kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: spring-music
  labels:
    app: spring-music
    app.kubernetes.io/component: spring-music
    app.kubernetes.io/instance: spring-music
    app.kubernetes.io/part-of: spring-music
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      annotations:
        openshift.io/imported-from: 'quay.io/edeandrea/spring-music:latest'
      from:
        kind: DockerImage
        name: 'quay.io/edeandrea/spring-music:latest'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  labels:
    app: spring-music
    app.kubernetes.io/component: spring-music
    app.kubernetes.io/instance: spring-music
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: spring-music
    app.openshift.io/runtime: spring-boot
    app.openshift.io/runtime-version: '11'
  name: spring-music
  annotations:
    app.openshift.io/connects-to: summit-lab-spring-music-db
    app.openshift.io/vcs-ref: pipeline
    app.openshift.io/vcs-uri: "https://github.com/edeandrea/summit-lab-spring-music"
spec:
  replicas: 1
  selector:
    deploymentconfig: spring-music
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-music
        deploymentconfig: spring-music
    spec:
      containers:
        - image: spring-music:latest
          imagePullPolicy: Always
          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: summit-lab-spring-music-db
                  key: database-name
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: summit-lab-spring-music-db
                  key: database-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: summit-lab-spring-music-db
                  key: database-password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://summit-lab-spring-music-db/$(DB_NAME)
          name: spring-music
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - spring-music
        from:
          kind: ImageStreamTag
          name: spring-music:latest
---
kind: Service
apiVersion: v1
metadata:
  name: spring-music
  labels:
    app: spring-music
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
  selector:
    deploymentconfig: spring-music
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  labels:
    app: spring-music
  name: spring-music
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: spring-music
    weight: 100
