apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: camel-k
  namespace: "{{ proj_nm_rh_operators }}"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: camel-k
  source: community-operators
  sourceNamespace: openshift-marketplace
