apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rhdg-server-auth
  namespace: "{{ proj_nm_demo }}"
  labels:
    app: spring-music-cdc
data:
  identities.yaml: >-
    Y3JlZGVudGlhbHM6CiAgLSB1c2VybmFtZTogZGV2ZWxvcGVyCiAgICBwYXNzd29yZDogZGV2ZWxvcGVyCiAgLSB1c2VybmFtZTogb3BlcmF0b3IKICAgIHBhc3N3b3JkOiBvcGVyYXRvcgo=
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rhdg-client-auth
  namespace: "{{ proj_nm_demo }}"
  labels:
    app: spring-music-cdc
stringData:
  username: developer
  password: developer
---
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: albums-rhdg
  namespace: "{{ proj_nm_demo }}"
  labels:
    app: spring-music-cdc
    app.kubernetes.io/part-of: albums-cache
spec:
  replicas: 2
  service:
    type: DataGrid
    container:
      storage: 2Gi
  expose:
    type: Route
  security:
    endpointSecretName: rhdg-server-auth
---
apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: albums
  namespace: "{{ proj_nm_demo }}"
  labels:
    app: spring-music-cdc
spec:
  adminAuth:
    secretName: rhdg-client-auth
  clusterName: albums-rhdg
  name: albums
  template: <infinispan><cache-container><distributed-cache name="albums" mode="SYNC" statistics="true" remote-timeout="17500"><persistence><file-store/></persistence><state-transfer enabled="true" timeout="60000"/><transaction mode="NONE"/><locking striping="false" concurrency-level="1000" acquire-timeout="15000"/></distributed-cache></cache-container></infinispan>
