- name: Provision Demo
  block:
    - name: "Create the temp directory {{ temp_dir }}"
      file:
        path: "{{ temp_dir }}"
        state: directory

    - name: "Log into OpenShift as admin"
      k8s_auth:
        username: "{{ ocp_admin }}"
        password: "{{ ocp_admin_pwd }}"
      register: k8s_auth_results

    - name: Get Cluster Wildcard domain
      include: ../../common/getClusterWildcardDomain.yml

    - name: Log out of OpenShift admin user
      when: k8s_auth_results.k8s_auth.api_key is defined
      k8s_auth:
        state: absent
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"

    - name: Deploy Container Security
      include_tasks: ./container-security.yml

    # - name: Deploy Serverless
    #   include_tasks: ./serverless.yml

    - name: "Log into OpenShift as project user"
      k8s_auth:
        username: "{{ ocp_proj_user }}"
        password: "{{ ocp_proj_user_pwd }}"
      register: k8s_auth_results

    - name: "Create {{ proj_nm_demo }} project if it doesn't already exist"
      include: ../../common/createProject.yml
      vars:
        proj_nm: "{{ proj_nm_demo }}"

    - name: Deploy default view role binding
      k8s:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        namespace: "{{ proj_nm_demo }}"
        force: yes
        definition: "{{ lookup('template', '../objects/default-view-role-binding.yml') }}"

    - name: Deploy certificates
      include_tasks: ./certificates.yml
    
    - name: "Deploy RH-SSO"
      include_tasks: ./rh-sso.yml

    - name: Deploy DB Resources
      include_tasks: ./db.yml

    - name: Deploy AMQ Streams
      include_tasks: ./amq-streams.yml

    - name: Deploy RHDG
      include_tasks: ./rhdg.yml

    - name: Deploy App
      include_tasks: ./app.yml

    - name: If OpenShift login succeeded try to log out
      when: k8s_auth_results.k8s_auth.api_key is defined
      k8s_auth:
        state: absent
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"

    - name: Deploy Camel-K
      include_tasks: ./camelk.yml

    - debug:
        msg: "Provisioning has completed. Please go to https://console-openshift-console.{{ cluster_wildcard_domain.resources[0].status.domain }}/k8s/cluster/projects/{{ proj_nm_demo }} to see the project. It may take a while for the application to finish building and deploying."

  always:
    - name: If OpenShift login succeeded try to log out
      when: k8s_auth_results.k8s_auth.api_key is defined
      k8s_auth:
        state: absent
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"

    - name: Delete temp dir
      file:
        state: absent
        path: "{{ temp_dir }}"
